#deploymentURIsLocal:
#  - "<my-local-url>" # e.g. http://my-service.sockshop-dev:8080
deploymentURIsPublic:
  - "http://tnt-aapl-svc.delivery-demo-staging.delivery-demo.stagingk3s.34.207.219.93.nip.io:80/"